const CONSTANTS = {
  PLACE_VISITED: "Place Visited",
  TRIP_STARTED: "Trip Started On",
  TRIP_ENDED: "Trip Ended on",
  TRAVEL_REASON: "Occassion",
  USER_NAME: "Name",
  DOB: "DOB",
  PHONE_NO: "Contact No",
  EMAIL_ID: "E-mail Id",
  AMOUNT_SPENDED: "Amount spent by me",
  AMOUNT_RECEIVED: "Total amount received",
  BALANCE_AMOUNT: "Total Balance",
  USER_ADDRESS: "Address",
  AMOUNT_RECEIVED_DATE: "Received Date",
  AMOUNT_SPENT_DATE: "Paid on",
  AMOUNT_PAID_FOR: "Paid For",
  PAYMENT_MODE: "Payment Mode",
  PLACE_ID: "placeId",
  USER_ID: "userId",
  EXPENSE_ID: "expenseId",
  MODE_OF_TRAVEL: "Mode of travel",
  HOME_PAGE: "Home_Page",
  INDIVIDUAL_USER_PAGE: "EachUserPage",
  USER_TRIP_EXPENSE: "TripExpenses",
  EXPENSE_TYPE_CREDIT: "Credit",
  EXPENSE_TYPE_DEBIT: "Debit",
  DELETE_BTN: "Delete",
  EDIT_BTN: "Edit",
  ADD_NEW_USER_BTN: "Add New User",
  ADD_NEW_EXPENSE_BTN: "Add New Expense",
  ADD_NEW_PLACE_BTN: "Add New Place",
  UPDATE_USER_DETAILS: "Update User Data",
  DELETE_USER_DATA: "Delete Data of ",
  CANCEL_BTN: "Cancel",
  CARD_HEADER_ADD_EXPENSE: "ADD NEW EXPENSE",
  CARD_HEADER_EDIT_EXPENSE: "EDIT EXPENSE DATA",
  CARD_HEADER_ADD_PLACE: "ADD NEW PLACE",
  CARD_HEADER_EDIT_EXPENSE: "EDIT PLACE DATA",
  CARD_HEADER_ADD_PLACE: "ADD USER PLACE",
  CARD_HEADER_EDIT_EXPENSE: "EDIT USER DATA",
  UPDATE: "Update",
  EXPENSE_TABLE_NAME: "Expenses Table",
  USERS_TABLE_NAME: "User Table",
};

export default CONSTANTS;
