const CONSTANTS = {
  PLACE_VISITED: "Place Visited",
  VISITED_ON: "Visted On",
  TRAVEL_REASON: "Occassion",
  USER_NAME: "Name",
  DOB: "DOB",
  PHONE_NO: "Contact No",
  EMAIL_ID: "E-mail Id",
  AMOUNT_SPENDED: "Amount spent by me",
  AMOUNT_RECEIVED: "Total amount received",
  BALANCE_AMOUNT: "Total Balance",
  USER_ADDRESS: "Address",
  AMOUNT_RECEIVED_DATE: "Received Date",
  AMOUNT_SPENT_DATE: "Paid on",
  AMOUNT_PAID_FOR: "Paid For",
  PAYMENT_MODE: "Payment Mode",
  PLACE_ID: "placeId",
  USER_ID: "userId",
  EXPENSE_ID: "expenseId",
  MODE_OF_TRAVEL: "Mode of travel",
  HOME_PAGE: "Home_Page",
  INDIVIDUAL_USER_PAGE: "EachUserPage",
  USER_TRIP_EXPENSE: "TripExpenses",
  EXPENSE_TYPE_CREDIT: "Credit",
  EXPENSE_TYPE_DEBIT: "Debit",
};

export default CONSTANTS;
